export const LACK_START_END_TIME = "You must set start and end time"
export const END_OVER_START = "End time must not over start time"
export const OLD_DATE = "Date is old"
export const SUCCESS_LOGIN ="Login successful"
export const FAILURE_LOGIN ="Login failed"